name: Node CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: madrun
    strategy:
      matrix:
        node-version:
          - 16.x
          - 17.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redrun
        run: npm i redrun -g
      - name: Install
        run: npm install -f
      - name: Bootstrap
        run: redrun bootstrap
      - name: Lint
        run: redrun fix:lint
      - name: Commit fixes
        uses: EndBug/add-and-commit@v7
        with:
          message: chore(${{ env.NAME }}) lint using actions
      - name: Coverage
        run: redrun coverage report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
